export const ROUTES = {
  ADMIN: "/admin",
  ADMIN_HELP: "/admin/help",
  LOGIN: "/authorization/login",
  DISPATCHER: "/dispatcher",
  DISPATCHER_HELP: "/dispatcher/help",
  DISPATCHER_ASSIGNMENTS: "/dispatcher/assignments",
  DISPATCHER_ACCIDENTS: "/dispatcher/accidents",
  DISPATCHER_INDICATIONS: "/dispatcher/indications",
  DISPATCHER_FORECAST: "/dispatcher/forecast",
  WORKER: "/worker",
  WORKER_HELP: "/worker/help",
  REDIRECT: "/redirect",
  LOCATION: "/dispatcher/location",
} as const;
